server:
  port: 8099

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user?serverTimezone=UTC&useUnicode=true&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456zx.
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual

    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat, wall

mybatis:
  mapper-locations: classpath:mapper/**/*.xml


logging:
  config: classpath:logback-spring.xml
  level:
    com.jay.mm: DEBUG
jay:
  mm:
    jwt: 7786df7fc3a34e26a61c034d5ec8245d